### ISSUE TITLE
Only events with start end time equal to the full hour supported

### ISSUE THREAD

**Issue by nidkil** [altinselimi/kalendar#23] opened 2018-11-06 08:59 UTC
Hi Altin,

I ran into a problem that events that do not start or end on the full hour throw an error (`Uncaught TypeError: r.getHours is not a function`). The problem seems to be the following line in kalendar-container.vue.

``` js
let start_is_midnight = from.getHours() + from.getMinutes() === 0;
```

In the codepen you provide you can test this with the following event.

``` js
  {
    from: "Tue Nov 05 2018 01:00:00",
    to: "Tue Nov 05 2018 02:30:00",
    date: "2018-11-05",
    data: {
      title: "My Birthday",
      description: "Lorem ipsum dolor sit amet."
    }
  }
```

Regards, nidkil

**Comment by altinselimi** [comment] 2018-11-06 11:50
@nidkil this is actually not a bug. The calendar uses the 'split_value' to create the cells. So if you add something like 1:30, you must make sure that 30%split_value === 0. That means you can set split value to 10 or 15 or 30, but by default its 20 so that's why it wasn't working. 

As I mentioned all these will be fixed and released in the next version of Kalendar. Which is going to be next month !

**Comment by nidkil** [comment] 2018-11-06 17:10
Ah missed that. It works. Thx!

I forked and changed your Codepen to demonstrate this (https://codepen.io/nidkil/pen/JeYYGr). I also made the event dates dynamic so that they are always displayed on the current date and made it possible to switch between day and month view.

**Comment by nidkil** [comment] 2018-12-21 20:39
@altinselimi how is the next version coming along? Still on schedule?

**Comment by altinselimi** [comment] 2018-12-22 13:00
Yeah, still working on it.

**Comment by altinselimi** [comment] 2019-03-17 00:34
@nidkil Finally caught some breath and had the opportunity to do some heavy work on the plugin rewrite. This bug will not be present ever again after v2 release :)

**Closed by altinselimi** 2019-03-17 00:34 UTC
Labels: bug, enhancement
