### ISSUE TITLE
TypeError: Cannot read property 'some' of undefined

### ISSUE THREAD

**Issue by johnymahony** [altinselimi/kalendar#67] opened 2020-05-01 08:53 UTC
If I click into the cell, to create new event, I got error.
TypeError: Cannot read property 'some' of undefined
    at VueComponent.clearCreatingLeftovers

![calendar2](https://user-images.githubusercontent.com/2997318/80794344-01d23800-8b9a-11ea-9dc9-182eee779466.PNG)
![calendar](https://user-images.githubusercontent.com/2997318/80794345-03036500-8b9a-11ea-985e-97016c20eac9.PNG)

**Comment by altinselimi** [comment] 2020-05-09 19:09
This is now fixed. It was a bug caused by a PR I merged a while back. Try it once more !

**Closed by altinselimi** 2020-05-09 19:09 UTC
